/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolRouteImport } from './routes/pool'
import { Route as PoolIdRouteImport } from './routes/pool.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRoute = PoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolIdRoute = PoolIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PoolRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pool': typeof PoolRouteWithChildren
  '/pool/$id': typeof PoolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pool': typeof PoolRouteWithChildren
  '/pool/$id': typeof PoolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pool': typeof PoolRouteWithChildren
  '/pool/$id': typeof PoolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pool' | '/pool/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pool' | '/pool/$id'
  id: '__root__' | '/' | '/pool' | '/pool/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoolRoute: typeof PoolRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$id': {
      id: '/pool/$id'
      path: '/$id'
      fullPath: '/pool/$id'
      preLoaderRoute: typeof PoolIdRouteImport
      parentRoute: typeof PoolRoute
    }
  }
}

interface PoolRouteChildren {
  PoolIdRoute: typeof PoolIdRoute
}

const PoolRouteChildren: PoolRouteChildren = {
  PoolIdRoute: PoolIdRoute,
}

const PoolRouteWithChildren = PoolRoute._addFileChildren(PoolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoolRoute: PoolRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
